kind: Deployment
apiVersion: apps/v1
metadata:
  name: pve_node_exporter_discovery
  labels:
    app: pve_node_exporter_discovery-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pve_node_exporter_discovery
  template:
    metadata:
      labels:
        app: pve_node_exporter_discovery
    spec:
      containers:
        - name: pve_node_exporter_discovery
          image: 14agerber/pve_node_exporter_discovery:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 24684
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 24684
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 24684
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources: {}

---

kind: Service
apiVersion: v1
metadata:
  name: pve_node_exporter_discovery
  labels:
    app: pve_node_exporter_discovery
spec:
  ports:
    - port: 24684
      targetPort: 24684
  selector:
    app: pve_node_exporter_discovery