kind: Deployment
apiVersion: apps/v1
metadata:
  name: pve-node-discovery
  labels:
    app: pve-node-discovery
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pve-node-discovery
  template:
    metadata:
      labels:
        app: pve-node-discovery
    spec:
      containers:
        - name: pve-node-discovery
          image: 14agerber/pve-node-discovery:1.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9951
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9951
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9951
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources: {}

---

kind: Service
apiVersion: v1
metadata:
  name: pve-node-discovery
  labels:
    app: pve-node-discovery
spec:
  ports:
    - port: 9951
      targetPort: 9951
  selector:
    app: pve-node-discovery